Rd comp windows
OpenSEMBA/fdtd pull request #55
Opened 2024-10-09 06:36 UTC by AlejandroMunozManterola

Includes instructions to compile Windows(intelLLVM)

2024-10-09 06:56 UTC, lmdiazangulo requested changes

2024-10-09 06:56 UTC, lmdiazangulo commented on README.md
> +This software requires [Windows BaseKit](https://registrationcenter-download.intel.com/akdlm/IRC_NAS/62641e01-1e8d-4ace-91d6-ae03f7f8a71f/w_BaseKit_p_2024.0.0.49563_offline.exe) and [Windows HPCKit](
I wouldn't include this link... it's too specific and they tend to change it all the time. I think it's better if you simply mention the packages.

2024-10-10 06:53 UTC, lmdiazangulo approved these changes

2024-10-10 06:54 UTC, AlejandroMunozManterola commented on README.md
> +This software requires [Windows BaseKit](https://registrationcenter-download.intel.com/akdlm/IRC_NAS/62641e01-1e8d-4ace-91d6-ae03f7f8a71f/w_BaseKit_p_2024.0.0.49563_offline.exe) and [Windows HPCKit](
Changed the URL from specific versions to the main webpages of the toolkits.
Additionally changed the ninja repository to one with an already compiled release.

2024-10-10 07:13 UTC, merged